services:
  - type: web
    name: movie-booking-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn moviebooking.wsgi:application --bind 0.0.0.0:${PORT:-8000} --timeout 120 --workers 3"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.15

  - type: cron
    name: keep-alive-ping
    runtime: python
    schedule: "*/14 * * * *"
    buildCommand: "pip install requests"
    startCommand: "python -c \"import requests; r = requests.get('https://movie-booking-system-iufr.onrender.com/health/'); print(r.status_code)\""
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.15
