# Generated by Django 4.2 on 2026-01-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_otp",
            field=models.CharField(
                blank=True,
                help_text="6-digit OTP for email verification",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of failed OTP verification attempts"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When OTP was generated", null=True
            ),
        ),
    ]
