# Generated by Django 6.0.2 on 2026-02-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_email_otp_userprofile_otp_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="otp_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
