# Generated by Django 5.2.7 on 2026-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_idempotency_key_alter_booking_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
