# Generated by Django 5.2.7 on 2026-01-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_initiated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
