# Generated by Django 5.2.7 on 2026-01-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_payment_initiated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="idempotency_key",
        ),
    ]
