# Generated by Django 5.2.7 on 2026-01-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_remove_booking_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="refund_notification_sent",
            field=models.BooleanField(
                default=False, help_text="Track if refund notification email was sent"
            ),
        ),
    ]
