# Generated by Django 5.2.7 on 2026-01-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_booking_refund_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="confirmation_email_sent",
            field=models.BooleanField(
                default=False, help_text="Track if confirmation email was sent"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="failure_email_sent",
            field=models.BooleanField(
                default=False, help_text="Track if payment failure email was sent"
            ),
        ),
    ]
