# Generated by Django 6.0.2 on 2026-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_confirmation_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_code_base64",
            field=models.TextField(
                blank=True,
                help_text="QR code as Base64 string for email/display",
                null=True,
            ),
        ),
    ]
