# Generated by Django 6.0.2 on 2026-02-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_booking_qr_code_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="qr_code",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="qr_code_base64",
        ),
    ]
