# Generated by Django 4.2 on 2026-01-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="reviewlike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reviewlike",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewlike",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.DeleteModel(
            name="Interest",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewLike",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
