# Generated by Django 6.0.2 on 2026-02-05 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_review_movie_remove_review_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="available_seats",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
